// Generated by gencpp from file vln_planner/ObjectCoordinates.msg
// DO NOT EDIT!


#ifndef VLN_PLANNER_MESSAGE_OBJECTCOORDINATES_H
#define VLN_PLANNER_MESSAGE_OBJECTCOORDINATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vln_planner/ObjectCoordinate.h>

namespace vln_planner
{
template <class ContainerAllocator>
struct ObjectCoordinates_
{
  typedef ObjectCoordinates_<ContainerAllocator> Type;

  ObjectCoordinates_()
    : header()
    , objects()  {
    }
  ObjectCoordinates_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vln_planner::ObjectCoordinate_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vln_planner::ObjectCoordinate_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::vln_planner::ObjectCoordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vln_planner::ObjectCoordinates_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectCoordinates_

typedef ::vln_planner::ObjectCoordinates_<std::allocator<void> > ObjectCoordinates;

typedef boost::shared_ptr< ::vln_planner::ObjectCoordinates > ObjectCoordinatesPtr;
typedef boost::shared_ptr< ::vln_planner::ObjectCoordinates const> ObjectCoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vln_planner::ObjectCoordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vln_planner::ObjectCoordinates_<ContainerAllocator1> & lhs, const ::vln_planner::ObjectCoordinates_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vln_planner::ObjectCoordinates_<ContainerAllocator1> & lhs, const ::vln_planner::ObjectCoordinates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vln_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vln_planner::ObjectCoordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vln_planner::ObjectCoordinates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vln_planner::ObjectCoordinates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0318b91e668fb7389ebc4d82bc5b870";
  }

  static const char* value(const ::vln_planner::ObjectCoordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0318b91e668fb73ULL;
  static const uint64_t static_value2 = 0x89ebc4d82bc5b870ULL;
};

template<class ContainerAllocator>
struct DataType< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vln_planner/ObjectCoordinates";
  }

  static const char* value(const ::vln_planner::ObjectCoordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# msg/ObjectCoordinates.msg\n"
"# 多物体的类别+坐标列表\n"
"std_msgs/Header header  # 消息头（时间戳+坐标系）\n"
"ObjectCoordinate[] objects  # 物体坐标列表\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vln_planner/ObjectCoordinate\n"
"# msg/ObjectCoordinate.msg\n"
"# 单个物体的类别名称和绝对坐标\n"
"string class_name       # 物体类别名称（如person/laptop/bottle）\n"
"geometry_msgs/Point point  # 物体的绝对坐标（x/y/z）\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vln_planner::ObjectCoordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectCoordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vln_planner::ObjectCoordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vln_planner::ObjectCoordinates_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::vln_planner::ObjectCoordinate_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLN_PLANNER_MESSAGE_OBJECTCOORDINATES_H
