// Generated by gencpp from file vln_planner/ObjectDetections.msg
// DO NOT EDIT!


#ifndef VLN_PLANNER_MESSAGE_OBJECTDETECTIONS_H
#define VLN_PLANNER_MESSAGE_OBJECTDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vln_planner/ObjectDetection.h>

namespace vln_planner
{
template <class ContainerAllocator>
struct ObjectDetections_
{
  typedef ObjectDetections_<ContainerAllocator> Type;

  ObjectDetections_()
    : header()
    , objects()  {
    }
  ObjectDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vln_planner::ObjectDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vln_planner::ObjectDetection_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::vln_planner::ObjectDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vln_planner::ObjectDetections_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetections_

typedef ::vln_planner::ObjectDetections_<std::allocator<void> > ObjectDetections;

typedef boost::shared_ptr< ::vln_planner::ObjectDetections > ObjectDetectionsPtr;
typedef boost::shared_ptr< ::vln_planner::ObjectDetections const> ObjectDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vln_planner::ObjectDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vln_planner::ObjectDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vln_planner::ObjectDetections_<ContainerAllocator1> & lhs, const ::vln_planner::ObjectDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vln_planner::ObjectDetections_<ContainerAllocator1> & lhs, const ::vln_planner::ObjectDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vln_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vln_planner::ObjectDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vln_planner::ObjectDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vln_planner::ObjectDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vln_planner::ObjectDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vln_planner::ObjectDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vln_planner::ObjectDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vln_planner::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce6350982d48c66f3e1a08ec1b02cb6f";
  }

  static const char* value(const ::vln_planner::ObjectDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce6350982d48c66fULL;
  static const uint64_t static_value2 = 0x3e1a08ec1b02cb6fULL;
};

template<class ContainerAllocator>
struct DataType< ::vln_planner::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vln_planner/ObjectDetections";
  }

  static const char* value(const ::vln_planner::ObjectDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vln_planner::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ObjectDetections.msg\n"
"Header header\n"
"ObjectDetection[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vln_planner/ObjectDetection\n"
"string class_name\n"
"float32 x_center #归一化\n"
"float32 y_center\n"
"float32 width\n"
"float32 height\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::vln_planner::ObjectDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vln_planner::ObjectDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vln_planner::ObjectDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vln_planner::ObjectDetections_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::vln_planner::ObjectDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLN_PLANNER_MESSAGE_OBJECTDETECTIONS_H
