// Generated by gencpp from file VLN_planner/ObjectCoordinate.msg
// DO NOT EDIT!


#ifndef VLN_PLANNER_MESSAGE_OBJECTCOORDINATE_H
#define VLN_PLANNER_MESSAGE_OBJECTCOORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace VLN_planner
{
template <class ContainerAllocator>
struct ObjectCoordinate_
{
  typedef ObjectCoordinate_<ContainerAllocator> Type;

  ObjectCoordinate_()
    : class_name()
    , point()  {
    }
  ObjectCoordinate_(const ContainerAllocator& _alloc)
    : class_name(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectCoordinate_

typedef ::VLN_planner::ObjectCoordinate_<std::allocator<void> > ObjectCoordinate;

typedef boost::shared_ptr< ::VLN_planner::ObjectCoordinate > ObjectCoordinatePtr;
typedef boost::shared_ptr< ::VLN_planner::ObjectCoordinate const> ObjectCoordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::VLN_planner::ObjectCoordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::VLN_planner::ObjectCoordinate_<ContainerAllocator1> & lhs, const ::VLN_planner::ObjectCoordinate_<ContainerAllocator2> & rhs)
{
  return lhs.class_name == rhs.class_name &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::VLN_planner::ObjectCoordinate_<ContainerAllocator1> & lhs, const ::VLN_planner::ObjectCoordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace VLN_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c88e551183bc43bf1db8b23e63043da";
  }

  static const char* value(const ::VLN_planner::ObjectCoordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c88e551183bc43bULL;
  static const uint64_t static_value2 = 0xf1db8b23e63043daULL;
};

template<class ContainerAllocator>
struct DataType< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "VLN_planner/ObjectCoordinate";
  }

  static const char* value(const ::VLN_planner::ObjectCoordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# msg/ObjectCoordinate.msg\n"
"# 单个物体的类别名称和绝对坐标\n"
"string class_name       # 物体类别名称（如person/laptop/bottle）\n"
"geometry_msgs/Point point  # 物体的绝对坐标（x/y/z）\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::VLN_planner::ObjectCoordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_name);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectCoordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::VLN_planner::ObjectCoordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::VLN_planner::ObjectCoordinate_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLN_PLANNER_MESSAGE_OBJECTCOORDINATE_H
