// Generated by gencpp from file yolo_detection_package/ObjectDetection.msg
// DO NOT EDIT!


#ifndef YOLO_DETECTION_PACKAGE_MESSAGE_OBJECTDETECTION_H
#define YOLO_DETECTION_PACKAGE_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_detection_package
{
template <class ContainerAllocator>
struct ObjectDetection_
{
  typedef ObjectDetection_<ContainerAllocator> Type;

  ObjectDetection_()
    : class_name()
    , x_center(0.0)
    , y_center(0.0)
    , width(0.0)
    , height(0.0)
    , confidence(0.0)  {
    }
  ObjectDetection_(const ContainerAllocator& _alloc)
    : class_name(_alloc)
    , x_center(0.0)
    , y_center(0.0)
    , width(0.0)
    , height(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _x_center_type;
  _x_center_type x_center;

   typedef float _y_center_type;
  _y_center_type y_center;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetection_

typedef ::yolo_detection_package::ObjectDetection_<std::allocator<void> > ObjectDetection;

typedef boost::shared_ptr< ::yolo_detection_package::ObjectDetection > ObjectDetectionPtr;
typedef boost::shared_ptr< ::yolo_detection_package::ObjectDetection const> ObjectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_detection_package::ObjectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_detection_package::ObjectDetection_<ContainerAllocator1> & lhs, const ::yolo_detection_package::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.class_name == rhs.class_name &&
    lhs.x_center == rhs.x_center &&
    lhs.y_center == rhs.y_center &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_detection_package::ObjectDetection_<ContainerAllocator1> & lhs, const ::yolo_detection_package::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_detection_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c42afd1b09ce5e8fc8ab40cda3991fcf";
  }

  static const char* value(const ::yolo_detection_package::ObjectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc42afd1b09ce5e8fULL;
  static const uint64_t static_value2 = 0xc8ab40cda3991fcfULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_detection_package/ObjectDetection";
  }

  static const char* value(const ::yolo_detection_package::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string class_name\n"
"float32 x_center #归一化\n"
"float32 y_center\n"
"float32 width\n"
"float32 height\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::yolo_detection_package::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_name);
      stream.next(m.x_center);
      stream.next(m.y_center);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_detection_package::ObjectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_detection_package::ObjectDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_center: ";
    Printer<float>::stream(s, indent + "  ", v.x_center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_center: ";
    Printer<float>::stream(s, indent + "  ", v.y_center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_DETECTION_PACKAGE_MESSAGE_OBJECTDETECTION_H
