(cl:defpackage VLN_planner-msg
  (:use )
  (:export
   "<OBJECTCOORDINATE>"
   "OBJECTCOORDINATE"
   "<OBJECTCOORDINATES>"
   "OBJECTCOORDINATES"
   "<OBJECTDETECTION>"
   "OBJECTDETECTION"
   "<OBJECTDETECTIONS>"
   "OBJECTDETECTIONS"
  ))

